botID: '' # Bot ID
botToken:  # Bot TOKEN
serverID: '' # Guild ID
ownerID: '' # Youre ID
developers: # Developers user ID list
  - ''
log_channel: '' # Log channel

# ===========================================================================
# BOT ACTIVITY
# ===========================================================================
BotActivitySettings:
  Enabled: true
  Type: "WATCHING" # WATCHING, PLAYING, COMPETING
  Interval: 30 # Time in seconds between status changes, It's recommended to keep it above 20-30 seconds to avoid getting ratelimited
  Statuses: # Valid Variables: {total-users}, {total-channels}, {total-messages}
    - "{total-users} users"
    - "{total-messages} messages"
    - "hybridstore.org"
